/*****************************************************************************
 * EECC381 - Program to determine the maximum percent error.  This program 
 * assumes that the data was generated by GenTestData.
*****************************************************************************/
#include <stdio.h>
#include <math.h>

#include "Equation.h"

/* Typemark for 16-bit Digital numbers */
typedef short int DigitalValues;

/*****************************************************************************
* Main program to correct digital measurements.
*****************************************************************************/
int main(int argc, char *argv[])
  {
   /* The error associated with an individual digital value */
   double Error;

   /* The maximum (in absolute value) percent error over all measurements */
   double MaxError = 0.0;

   /* Digital value to be read from stdin */
   DigitalValues DigitalValue = 0;

   /* The floating-point "counter" */
   double PhysicalQuantity = MIN_ACCURATE_SENSOR; 


   while (scanf("%hd", &DigitalValue) != EOF)
     {
      /* Determine the percent error */
      Error = fabs(DigitalValue - (int)(0.5 + PhysicalQuantity / MAX_SENSOR * (double)MAX_A2D)) / (double)MAX_A2D * 100.0;

      /* Update the expected physical value */
      PhysicalQuantity += (MAX_SENSOR - MIN_SENSOR) / NUM_STEPS;

      /* Update the maximum error value (if appropriate) */
      if (Error > MaxError) MaxError = Error;
     } /* for() */

   /* Display the maximum percent error found */
   printf("Maximum Error = %4.4lf%%\n", MaxError);

   return 0;
  } /* main() */
